version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    container_name: real_world
    restart: always
    ports:
      - 6543:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=real_world_db